// <auto-generated />
using System;
using AspNetCoreSamplesJwt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreSamplesJwt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200105054905_AddJwtTokenData")]
    partial class AddJwtTokenData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("AspNetCoreSamplesJwt.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("AspNetCoreSamplesJwt.Services.JwtRefreshTokenData", b =>
                {
                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("RefreshToken");

                    b.ToTable("JwtRefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
